import Header from "@/components/Header";
import "./globals.css";
import localFont from "next/font/local";
import { OrpheusPro, Twentieth } from "@/utils/customFonts";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Rose-website",
  description: "Generated by create next app",
  icons: {
    icon: "/fav-icon.svg", // path to your favicon
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${Twentieth.variable} ${OrpheusPro.variable}  `}>
        <Header />

        <main className="flex flex-col min-h-screen">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
